#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
scripts/bootstrap

test -z "$NODE_ENV" &&
  NODE_ENV='development'

# boot the app and any other necessary processes.

if [ "$NODE_ENV" = "development"]; then
  webpack-dev-server --history-api-fallback --hot --inline --progress --colors --port 3000
else
  webpack --progress --colors
fi




